// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Signup() {
    driver.Navigate().GoToUrl("https://gs1eg-is-mygs1-fe-beta.azurewebsites.net/auth/signup");
    driver.Manage().Window.Size = new System.Drawing.Size(1148, 799);
    driver.FindElement(By.CssSelector(".ng-tns-c43-3 > .mat-form-field-infix")).Click();
    driver.FindElement(By.Id("mat-input-0")).SendKeys("aa");
    driver.FindElement(By.Id("mat-input-1")).SendKeys("aa");
    driver.FindElement(By.Id("mat-input-2")).SendKeys("aa@aa.aattww");
    {
      var element = driver.FindElement(By.CssSelector(".action-div > .ng-star-inserted"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".action-div > .ng-star-inserted")).Click();
    driver.FindElement(By.CssSelector(".ng-dirty > .row > .mat-form-field-div-flag")).Click();
    driver.FindElement(By.CssSelector("#phone")).SendKeys(Keys.Backspace);
    driver.FindElement(By.CssSelector("#phone")).Click();
    driver.FindElement(By.CssSelector("#phone")).SendKeys("0123456789011111");
    driver.FindElement(By.CssSelector(".ng-tns-c49-7 > .mat-select-arrow")).Click();
    driver.FindElement(By.CssSelector(".mat-select-placeholder")).Click();
    driver.FindElement(By.CssSelector("#mat-option-5 > .mat-option-text")).Click();
    driver.FindElement(By.CssSelector(".action-div > .ng-star-inserted")).Click();
    driver.FindElement(By.Id("mat-input-3")).SendKeys("12345678");
    driver.FindElement(By.CssSelector(".ng-tns-c43-9 > .mat-form-field-infix")).Click();
    driver.FindElement(By.Id("mat-input-4")).SendKeys("12345678");
    driver.FindElement(By.CssSelector(".mat-checkbox-inner-container")).Click();
    driver.FindElement(By.CssSelector(".action-div > .ng-star-inserted")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".action-div > .ng-star-inserted"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".btnSmall > .mat-button-wrapper"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector(".btnSmall > .mat-button-wrapper")).Click();
  }
}
